//! `template new`가 생성할 뼈대 파일 집합의 순수 정의 — `SkeletonEntry`, `skeleton`.

/// `template new`가 스토어에 쓸 항목 하나. `content: None`이면 디렉토리, `Some`이면 그 내용의
/// 파일. `rel`은 템플릿 루트 기준 상대경로(`/` 구분, 단일 컴포넌트 경계 안 — `safe_rel_path`로
/// 검증 가능).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkeletonEntry {
    pub rel: String,
    pub content: Option<&'static str>,
}

fn entry(rel: &str, content: Option<&'static str>) -> SkeletonEntry {
    SkeletonEntry {
        rel: rel.to_string(),
        content,
    }
}

const SIMPLE_MANIFEST: &str = r#"# scaffold.toml -- template manifest.
# Each [[questions]] entry becomes a top-level render variable, e.g. {{ description }}.
# See files/README.md.jinja for how it is used.

[[questions]]
name = "description"
type = "string"
prompt = "Short project description"
default = "A new project"
"#;

const FULL_MANIFEST: &str = r#"# scaffold.toml -- template manifest.
# Each [[questions]] entry becomes a top-level render variable, e.g. {{ description }}.
# See files/README.md.jinja and files/NOTES.md.jinja for how it is used.

[[questions]]
name = "description"
type = "string"
prompt = "Short project description"
default = "A new project"

[[hooks.after]]
run = "echo 'project scaffolded'"
"#;

const README_JINJA: &str = "# {{ scaffolder.name }}\n\n{{ description }}\n";

const HEADER_PARTIAL: &str = "Generated by the {{ scaffolder.name }} template.\n";

const SAMPLE_DATA_TOML: &str = "[project]\ntagline = \"built with scaffolder\"\n";

const NOTES_JINJA: &str = "{% include \"header.txt\" %}\n\n{{ data.project.tagline }}\n";

/// `full=false`면 최소 유효 템플릿(scaffold.toml+files/+샘플 파일), `full=true`면 추가로
/// partials/·data/·hooks/ 샘플을 포함한다. 샘플 자체가 유효 템플릿이 되도록 유지한다 — 파싱
/// 가능한 manifest, 문법에 맞는 파일명, 컴파일 가능한 jinja, 존재하는 partial 참조, 충돌 없음
/// (아래 테스트가 교차검증).
pub fn skeleton(full: bool) -> Vec<SkeletonEntry> {
    let manifest = if full { FULL_MANIFEST } else { SIMPLE_MANIFEST };

    let mut entries = vec![
        entry("scaffold.toml", Some(manifest)),
        entry("files", None),
        entry("files/README.md.jinja", Some(README_JINJA)),
    ];

    if full {
        entries.push(entry("partials", None));
        entries.push(entry("partials/header.txt", Some(HEADER_PARTIAL)));
        entries.push(entry("data", None));
        entries.push(entry("data/sample.toml", Some(SAMPLE_DATA_TOML)));
        entries.push(entry("files/NOTES.md.jinja", Some(NOTES_JINJA)));
        entries.push(entry("hooks", None));
        entries.push(entry("hooks/before", None));
        entries.push(entry("hooks/after", None));
    }

    entries
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    use crate::domain::name::parse_file_name;
    use crate::domain::place::safe_rel_path;

    #[test]
    fn simple_skeleton_has_manifest_files_dir_and_sample() {
        let entries = skeleton(false);
        assert!(entries
            .iter()
            .any(|e| e.rel == "scaffold.toml" && e.content.is_some()));
        assert!(entries.iter().any(|e| e.rel == "files" && e.content.is_none()));
        assert!(entries
            .iter()
            .any(|e| e.rel == "files/README.md.jinja" && e.content.is_some()));
    }

    #[test]
    fn simple_skeleton_excludes_full_only_entries() {
        let entries = skeleton(false);
        for prefix in ["partials", "data", "hooks"] {
            assert!(
                !entries
                    .iter()
                    .any(|e| e.rel == prefix || e.rel.starts_with(&format!("{prefix}/"))),
                "simple skeleton must not contain {prefix}"
            );
        }
    }

    #[test]
    fn full_skeleton_adds_partials_data_hooks_and_extra_sample() {
        let entries = skeleton(true);
        for rel in [
            "partials",
            "partials/header.txt",
            "data",
            "data/sample.toml",
            "files/NOTES.md.jinja",
            "hooks",
            "hooks/before",
            "hooks/after",
        ] {
            assert!(entries.iter().any(|e| e.rel == rel), "missing entry {rel}");
        }
    }

    #[test]
    fn full_manifest_differs_from_simple_and_declares_a_hook() {
        let simple = skeleton(false);
        let full = skeleton(true);
        let simple_manifest = simple
            .iter()
            .find(|e| e.rel == "scaffold.toml")
            .and_then(|e| e.content)
            .expect("simple manifest content");
        let full_manifest = full
            .iter()
            .find(|e| e.rel == "scaffold.toml")
            .and_then(|e| e.content)
            .expect("full manifest content");

        assert_ne!(simple_manifest, full_manifest);
        assert!(full_manifest.contains("hooks.after"));
        assert!(!simple_manifest.contains("hooks."));
    }

    #[test]
    fn every_entry_rel_is_within_single_component_boundary() {
        for entries in [skeleton(false), skeleton(true)] {
            for entry in &entries {
                assert!(
                    safe_rel_path(&entry.rel).is_ok(),
                    "rel {:?} escapes root",
                    entry.rel
                );
            }
        }
    }

    #[test]
    fn no_duplicate_rel_entries() {
        for entries in [skeleton(false), skeleton(true)] {
            let mut seen = HashSet::new();
            for entry in &entries {
                assert!(seen.insert(entry.rel.clone()), "duplicate rel {:?}", entry.rel);
            }
        }
    }

    #[test]
    fn directory_entries_have_no_content_file_entries_are_nonempty() {
        for entries in [skeleton(false), skeleton(true)] {
            for entry in &entries {
                if let Some(content) = entry.content {
                    assert!(!content.is_empty(), "file entry {:?} has empty content", entry.rel);
                }
            }
        }
    }

    #[test]
    fn sample_file_names_pass_file_name_grammar_and_render_via_jinja_suffix() {
        for entries in [skeleton(false), skeleton(true)] {
            for entry in &entries {
                let Some(basename) = entry.rel.strip_prefix("files/") else {
                    continue;
                };
                if entry.content.is_none() {
                    continue;
                }
                let parsed = parse_file_name(basename)
                    .unwrap_or_else(|e| panic!("{basename} should be a valid file name: {e}"));
                assert!(parsed.render, "{basename} should render (.jinja)");
            }
        }
    }

    #[test]
    fn no_source_conflicts_among_files_entries() {
        for entries in [skeleton(false), skeleton(true)] {
            let mut outputs = HashSet::new();
            for entry in &entries {
                let Some(basename) = entry.rel.strip_prefix("files/") else {
                    continue;
                };
                if entry.content.is_none() {
                    continue;
                }
                let parsed = parse_file_name(basename).expect("valid file name");
                assert!(
                    outputs.insert(parsed.output_base.clone()),
                    "conflicting output {}",
                    parsed.output_base
                );
            }
        }
    }
}
