//! Pure definition of the skeleton files `template new` creates — `SkeletonEntry`, `skeleton`.

/// One entry `template new` writes to the store. `content: None` is a directory, `Some` is a
/// file with that content. `rel` is relative to the template root (`/`-separated, within the
/// single-component boundary checked by `safe_rel_path`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkeletonEntry {
    pub rel: String,
    pub content: Option<&'static str>,
}

fn entry(rel: &str, content: Option<&'static str>) -> SkeletonEntry {
    SkeletonEntry {
        rel: rel.to_string(),
        content,
    }
}

const SIMPLE_MANIFEST: &str = r#"# scaffold.toml -- template manifest.
# Each [[questions]] entry becomes a top-level render variable, e.g. {{ description }}.
# See files/README.md.jinja for how it is used.

[[questions]]
name = "description"
type = "string"
prompt = "Short project description"
default = "A new project"
"#;

const FULL_MANIFEST: &str = r#"# scaffold.toml -- template manifest.
# Each [[questions]] entry becomes a top-level render variable, e.g. {{ description }}.
# See files/README.md.jinja and files/NOTES.md.jinja for how it is used.

[[questions]]
name = "description"
type = "string"
prompt = "Short project description"
default = "A new project"

[[hooks.after]]
run = "echo 'project scaffolded'"
"#;

const README_JINJA: &str = "# {{ scaffolder.name }}\n\n{{ description }}\n";

const HEADER_PARTIAL: &str = "Generated by the {{ scaffolder.name }} template.\n";

const SAMPLE_DATA_TOML: &str = "[project]\ntagline = \"built with scaffolder\"\n";

const NOTES_JINJA: &str = "{% include \"header.txt\" %}\n\n{{ data.project.tagline }}\n";

/// `full=false` yields a minimal valid template (`scaffold.toml` + `files/` + a sample);
/// `full=true` adds `partials/`, `data/`, and `hooks/` samples. The samples must themselves
/// form a valid template — parseable manifest, grammatical file names, compilable jinja,
/// resolvable partial references, no conflicts (cross-checked by the tests below).
pub fn skeleton(full: bool) -> Vec<SkeletonEntry> {
    let manifest = if full { FULL_MANIFEST } else { SIMPLE_MANIFEST };

    let mut entries = vec![
        entry("scaffold.toml", Some(manifest)),
        entry("files", None),
        entry("files/README.md.jinja", Some(README_JINJA)),
    ];

    if full {
        entries.push(entry("partials", None));
        entries.push(entry("partials/header.txt", Some(HEADER_PARTIAL)));
        entries.push(entry("data", None));
        entries.push(entry("data/sample.toml", Some(SAMPLE_DATA_TOML)));
        entries.push(entry("files/NOTES.md.jinja", Some(NOTES_JINJA)));
        entries.push(entry("hooks", None));
        entries.push(entry("hooks/before", None));
        entries.push(entry("hooks/after", None));
    }

    entries
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    use crate::domain::name::parse_file_name;
    use crate::domain::place::safe_rel_path;

    #[test]
    fn simple_skeleton_excludes_full_only_entries() {
        let entries = skeleton(false);
        for prefix in ["partials", "data", "hooks"] {
            assert!(
                !entries
                    .iter()
                    .any(|e| e.rel == prefix || e.rel.starts_with(&format!("{prefix}/"))),
                "simple skeleton must not contain {prefix}"
            );
        }
    }

    #[test]
    fn every_entry_rel_is_within_single_component_boundary() {
        for entries in [skeleton(false), skeleton(true)] {
            for entry in &entries {
                assert!(
                    safe_rel_path(&entry.rel).is_ok(),
                    "rel {:?} escapes root",
                    entry.rel
                );
            }
        }
    }

    #[test]
    fn no_duplicate_rel_entries() {
        for entries in [skeleton(false), skeleton(true)] {
            let mut seen = HashSet::new();
            for entry in &entries {
                assert!(
                    seen.insert(entry.rel.clone()),
                    "duplicate rel {:?}",
                    entry.rel
                );
            }
        }
    }

    #[test]
    fn sample_file_names_pass_file_name_grammar_and_render_via_jinja_suffix() {
        for entries in [skeleton(false), skeleton(true)] {
            for entry in &entries {
                let Some(basename) = entry.rel.strip_prefix("files/") else {
                    continue;
                };
                if entry.content.is_none() {
                    continue;
                }
                let parsed = parse_file_name(basename)
                    .unwrap_or_else(|e| panic!("{basename} should be a valid file name: {e}"));
                assert!(parsed.render, "{basename} should render (.jinja)");
            }
        }
    }

    #[test]
    fn no_source_conflicts_among_files_entries() {
        for entries in [skeleton(false), skeleton(true)] {
            let mut outputs = HashSet::new();
            for entry in &entries {
                let Some(basename) = entry.rel.strip_prefix("files/") else {
                    continue;
                };
                if entry.content.is_none() {
                    continue;
                }
                let parsed = parse_file_name(basename).expect("valid file name");
                assert!(
                    outputs.insert(parsed.output_base.clone()),
                    "conflicting output {}",
                    parsed.output_base
                );
            }
        }
    }
}
