//! `domain::skeleton::skeleton` 샘플이 실제 파이프라인(manifest 파싱·partials·data·render)을
//! 통과하는 유효 템플릿인지 교차검증한다. `domain::skeleton`의 프로덕션/유닛 테스트는 순수
//! domain만 참조해야 하므로(레이어드 아키텍처), infra를 걸치는 검증은 통합 테스트로 분리한다.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use tempfile::TempDir;

use scaffolder::domain::answer::{AnswerValue, ScaffolderBuiltins, build_context};
use scaffolder::domain::data::DataSource;
use scaffolder::domain::manifest::ManifestSource;
use scaffolder::domain::render::{PartialSource, Renderer};
use scaffolder::domain::skeleton::{SkeletonEntry, skeleton};
use scaffolder::infra::load::data::FsDataSource;
use scaffolder::infra::load::manifest::TomlManifestSource;
use scaffolder::infra::load::partials::FsPartialSource;
use scaffolder::infra::render::render::MiniJinjaRenderer;

fn materialize(entries: &[SkeletonEntry], root: &Path) {
    for entry in entries {
        let path = root.join(&entry.rel);
        match entry.content {
            None => fs::create_dir_all(&path).expect("mkdir"),
            Some(content) => {
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).expect("mkdir parent");
                }
                fs::write(&path, content).expect("write file");
            }
        }
    }
}

fn manifest_content(entries: &[SkeletonEntry]) -> &'static str {
    entries
        .iter()
        .find(|e| e.rel == "scaffold.toml")
        .and_then(|e| e.content)
        .expect("scaffold.toml entry must have content")
}

fn builtins() -> ScaffolderBuiltins {
    ScaffolderBuiltins {
        name: "demo".to_string(),
        target: std::path::PathBuf::from("/tmp/demo"),
        os: "macos".to_string(),
        arch: "aarch64".to_string(),
        username: "tester".to_string(),
    }
}

#[test]
fn simple_manifest_parses_with_expected_question() {
    let dir = TempDir::new().expect("tempdir");
    let path = dir.path().join("scaffold.toml");
    fs::write(&path, manifest_content(&skeleton(false))).expect("write manifest");
    let source = TomlManifestSource {
        root_canon: dir.path().canonicalize().unwrap(),
        trust: false,
    };

    let manifest = source.load(&path).expect("simple manifest should parse");

    assert_eq!(manifest.questions.len(), 1);
    assert_eq!(manifest.questions[0].name, "description");
    assert!(manifest.hooks.before.is_empty());
    assert!(manifest.hooks.after.is_empty());
}

#[test]
fn full_manifest_parses_with_after_hook() {
    let dir = TempDir::new().expect("tempdir");
    let path = dir.path().join("scaffold.toml");
    fs::write(&path, manifest_content(&skeleton(true))).expect("write manifest");
    let source = TomlManifestSource {
        root_canon: dir.path().canonicalize().unwrap(),
        trust: false,
    };

    let manifest = source.load(&path).expect("full manifest should parse");

    assert_eq!(manifest.questions.len(), 1);
    assert_eq!(manifest.hooks.after.len(), 1);
    assert!(manifest.hooks.after[0].run.contains("scaffolded"));
}

#[test]
fn full_skeleton_samples_render_with_partials_and_data() {
    let dir = TempDir::new().expect("tempdir");
    materialize(&skeleton(true), dir.path());
    let root_canon = dir.path().canonicalize().unwrap();

    let manifest_source = TomlManifestSource {
        root_canon: root_canon.clone(),
        trust: false,
    };
    let manifest = manifest_source
        .load(&dir.path().join("scaffold.toml"))
        .expect("manifest parses");

    let partial_source = FsPartialSource {
        root_canon: root_canon.clone(),
        trust: false,
    };
    let partials = partial_source.load(dir.path()).expect("partials load");
    assert!(partials.contains_key("header.txt"));

    let data_source = FsDataSource {
        root_canon: root_canon.clone(),
        trust: false,
    };
    let data = data_source
        .load(dir.path(), manifest.data.clone())
        .expect("data loads");

    let mut answers = BTreeMap::new();
    answers.insert(
        "description".to_string(),
        AnswerValue::Text("Demo project".to_string()),
    );
    let ctx = build_context(answers, Some(data), builtins());

    let renderer = MiniJinjaRenderer::with_partials(partials).expect("renderer builds");

    let readme_source =
        fs::read_to_string(dir.path().join("files/README.md.jinja")).expect("read README source");
    let readme = renderer
        .render_str(&readme_source, &ctx)
        .expect("README renders");
    assert!(readme.contains("Demo project"));

    let notes_source =
        fs::read_to_string(dir.path().join("files/NOTES.md.jinja")).expect("read NOTES source");
    let notes = renderer
        .render_str(&notes_source, &ctx)
        .expect("NOTES renders");
    assert!(notes.contains("Generated by the demo template."));
    assert!(notes.contains("built with scaffolder"));
}
