FROM rust:{{ data.msrv }}-slim AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/{{ scaffolder.name | kebab_case }} /usr/local/bin/{{ scaffolder.name | kebab_case }}
CMD ["{{ scaffolder.name | kebab_case }}"]
